# Kafka配置
kafka:
  # 基础连接配置
  bootstrap-servers: localhost:9092
  security:
    protocol: PLAINTEXT
    sasl:
      mechanism: PLAIN
      username: ""
      password: ""
  
  # 消费者配置
  consumer:
    # 默认消费组
    group-id: default-consumer-group
    # 自动提交偏移量
    enable-auto-commit: true
    auto-commit-interval: 1000
    # 会话超时时间
    session-timeout: 30000
    # 心跳间隔
    heartbeat-interval: 10000
    # 请求超时时间
    request-timeout: 40000
    # 重试间隔
    retry-backoff: 1000
    # 最大拉取间隔
    max-poll-interval: 300000
    # 批量拉取大小
    max-poll-records: 500
    # 分区分配策略
    partition-assignment-strategy: org.apache.kafka.clients.consumer.RangeAssignor
    # 反序列化器
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  
  # 生产者配置（如果需要）
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 1
    buffer-memory: 33554432
  
  # 主题配置
  topics:
    # 默认主题
    default: default-topic
    # 死信队列主题
    dlq: dlq-topic
    # 重试主题
    retry: retry-topic
  
  # 消费配置
  consume:
    # 默认消费模式
    default-mode: PUSH
    # 默认消费类型
    default-type: CLUSTERING
    # 默认消费顺序
    default-order: CONCURRENT
    # 默认批量大小
    default-batch-size: 100
    # 默认重试次数
    default-max-retry: 3
    # 默认超时时间
    default-timeout: 30000
