# DeepSearch Service 主配置文件
spring:
  application:
    name: messages-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
    lazy-initialization: false
  autoconfigure:
    exclude: []
  config:
    import:
      - optional:classpath:application-message-service.yml

# 服务配置
service:
  name: messages-service
  version: 1.0.0

