# Kafka配置
# 所有配置都从环境变量或配置文件读取，避免硬编码
kafka:
  # 基础连接配置
  bootstrap-servers:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  
  # 安全配置
  security:
    protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    sasl:
      mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      username: ${KAFKA_SASL_USERNAME:}
      password: ${KAFKA_SASL_PASSWORD:}
  
  # 消费者配置
  consumer:
    # 基础配置
    group-id: ${KAFKA_CONSUMER_GROUP_ID:default-consumer-group}
    client-id: ${KAFKA_CONSUMER_CLIENT_ID:default-consumer-client}
    enable-auto-commit: ${KAFKA_CONSUMER_ENABLE_AUTO_COMMIT:false}
    auto-commit-interval: ${KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL:1000}
    session-timeout: ${KAFKA_CONSUMER_SESSION_TIMEOUT:30000}
    heartbeat-interval: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL:10000}
    request-timeout: ${KAFKA_CONSUMER_REQUEST_TIMEOUT:40000}
    retry-backoff: ${KAFKA_CONSUMER_RETRY_BACKOFF:1000}
    max-poll-interval: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL:300000}
    max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:500}
    max-poll-bytes: ${KAFKA_CONSUMER_MAX_POLL_BYTES:52428800}
    connections-max-idle-ms: ${KAFKA_CONSUMER_CONNECTIONS_MAX_IDLE_MS:540000}
    metadata-max-age-ms: ${KAFKA_CONSUMER_METADATA_MAX_AGE_MS:300000}
    reconnect-backoff-ms: ${KAFKA_CONSUMER_RECONNECT_BACKOFF_MS:50}
    reconnect-backoff-max-ms: ${KAFKA_CONSUMER_RECONNECT_BACKOFF_MAX_MS:1000}
    retry-backoff-max-ms: ${KAFKA_CONSUMER_RETRY_BACKOFF_MAX_MS:1000}
    partition-assignment-strategy: ${KAFKA_CONSUMER_PARTITION_ASSIGNMENT_STRATEGY:org.apache.kafka.clients.consumer.RangeAssignor}
    key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
    value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
    
    # 消费组配置
    protocol: ${KAFKA_CONSUMER_GROUP_PROTOCOL:range}
    rebalance-timeout-ms: ${KAFKA_CONSUMER_REBALANCE_TIMEOUT_MS:60000}
    coordinator-address: ${KAFKA_CONSUMER_COORDINATOR_ADDRESS:}
    group-enabled: ${KAFKA_CONSUMER_GROUP_ENABLED:true}
    
    # 偏移量管理配置
    auto-offset-reset: ${KAFKA_CONSUMER_AUTO_OFFSET_RESET:latest}
    commit-timeout-ms: ${KAFKA_CONSUMER_COMMIT_TIMEOUT_MS:5000}
    commit-retry-count: ${KAFKA_CONSUMER_COMMIT_RETRY_COUNT:3}
    commit-retry-interval-ms: ${KAFKA_CONSUMER_COMMIT_RETRY_INTERVAL_MS:1000}
    enable-offset-cache: ${KAFKA_CONSUMER_ENABLE_OFFSET_CACHE:true}
    offset-cache-size: ${KAFKA_CONSUMER_OFFSET_CACHE_SIZE:1000}
    offset-cache-expire-ms: ${KAFKA_CONSUMER_OFFSET_CACHE_EXPIRE_MS:300000}
    
    # 批量消费配置
    batch-enabled: ${KAFKA_CONSUMER_BATCH_ENABLED:true}
    batch-size: ${KAFKA_CONSUMER_BATCH_SIZE:100}
    batch-timeout-ms: ${KAFKA_CONSUMER_BATCH_TIMEOUT_MS:1000}
    batch-thread-pool-size: ${KAFKA_CONSUMER_BATCH_THREAD_POOL_SIZE:4}
    batch-queue-size: ${KAFKA_CONSUMER_BATCH_QUEUE_SIZE:1000}
    batch-strategy: ${KAFKA_CONSUMER_BATCH_STRATEGY:FIXED_SIZE}
    batch-max-wait-time-ms: ${KAFKA_CONSUMER_BATCH_MAX_WAIT_TIME_MS:5000}
    
    # 顺序消费配置
    order-enabled: ${KAFKA_CONSUMER_ORDER_ENABLED:false}
    order-partition-count: ${KAFKA_CONSUMER_ORDER_PARTITION_COUNT:1}
    order-thread-count: ${KAFKA_CONSUMER_ORDER_THREAD_COUNT:1}
    order-timeout-ms: ${KAFKA_CONSUMER_ORDER_TIMEOUT_MS:30000}
    order-retry-count: ${KAFKA_CONSUMER_ORDER_RETRY_COUNT:3}
    order-retry-interval-ms: ${KAFKA_CONSUMER_ORDER_RETRY_INTERVAL_MS:1000}
    order-strategy: ${KAFKA_CONSUMER_ORDER_STRATEGY:PARTITION_BASED}
    
    # 重试配置
    retry-enabled: ${KAFKA_CONSUMER_RETRY_ENABLED:true}
    max-retries: ${KAFKA_CONSUMER_MAX_RETRIES:3}
    retry-interval-ms: ${KAFKA_CONSUMER_RETRY_INTERVAL_MS:1000}
    retry-backoff-strategy: ${KAFKA_CONSUMER_RETRY_BACKOFF_STRATEGY:EXPONENTIAL}
    retry-backoff-multiplier: ${KAFKA_CONSUMER_RETRY_BACKOFF_MULTIPLIER:2.0}
    max-retry-interval-ms: ${KAFKA_CONSUMER_MAX_RETRY_INTERVAL_MS:60000}
    retryable-exceptions: ${KAFKA_CONSUMER_RETRYABLE_EXCEPTIONS:org.apache.kafka.common.errors.RetriableException,java.net.SocketTimeoutException,java.net.ConnectException}
  
  # 生产者配置
  producer:
    bootstrap-servers: ${KAFKA_PRODUCER_BOOTSTRAP_SERVERS:localhost:9092}
    key-serializer: ${KAFKA_PRODUCER_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
    value-serializer: ${KAFKA_PRODUCER_VALUE_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
    acks: ${KAFKA_PRODUCER_ACKS:all}
    retries: ${KAFKA_PRODUCER_RETRIES:3}
    batch-size: ${KAFKA_PRODUCER_BATCH_SIZE:16384}
    linger-ms: ${KAFKA_PRODUCER_LINGER_MS:1}
    buffer-memory: ${KAFKA_PRODUCER_BUFFER_MEMORY:33554432}
  
  # 主题配置
  topics:
    default-topic: ${KAFKA_TOPICS_DEFAULT:default-topic}
    dlq: ${KAFKA_TOPICS_DLQ:dlq-topic}
    retry: ${KAFKA_TOPICS_RETRY:retry-topic}
  
  # 消费配置
  consume:
    default-mode: ${KAFKA_CONSUME_DEFAULT_MODE:PUSH}
    default-type: ${KAFKA_CONSUME_DEFAULT_TYPE:CLUSTERING}
    default-order: ${KAFKA_CONSUME_DEFAULT_ORDER:CONCURRENT}
    default-batch-size: ${KAFKA_CONSUME_DEFAULT_BATCH_SIZE:100}
    default-max-retry: ${KAFKA_CONSUME_DEFAULT_MAX_RETRY:3}
    default-timeout: ${KAFKA_CONSUME_DEFAULT_TIMEOUT:30000}

# 配置说明：
# 1. 所有配置都支持环境变量覆盖，格式：${ENV_VAR_NAME:default_value}
# 2. 环境变量优先级高于配置文件
# 3. 如果没有环境变量，则使用配置文件中的默认值
# 4. 支持不同环境的配置覆盖（dev, test, prod等）
