# 测试环境配置
spring:
  # Redis配置 - 测试环境
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 1  # 使用不同的数据库避免影响生产数据
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 4
          max-wait: -1ms
          max-idle: 4
          min-idle: 0

# 消息服务配置 - 测试环境
message:
  service:
    # 消息服务类型
    type: rocketmq
    
    # 是否启用消息轨迹追踪
    trace-enabled: false
    
    # 消息发送重试次数
    send-retry-times: 1
    
    # 消息发送超时时间（毫秒）
    send-timeout-ms: 3000
    
    # 最大批量发送消息数量
    max-batch-size: 10
    
    # RocketMQ配置 - 测试环境
    rocketmq:
      enabled: false  # 测试环境禁用RocketMQ
      name-server: localhost:9876
      producer-group: jiangyang-test-producer-group
      consumer-group: jiangyang-test-consumer-group
      compression-strategy: LZ4
      retry-sync-times: 1
      retry-async-times: 1
      queue-count-per-topic: 1
      message-retention-hours: 1

# Dubbo配置 - 测试环境
dubbo:
  application:
    name: messages-service
    qos-enable: false
    # 配置唯一的缓存路径，避免多实例冲突
    metadata-type: local
    # 禁用文件缓存，使用内存缓存
    cache-file: false
    # 配置应用实例ID，确保唯一性
    environment: test
  protocol:
    name: dubbo
    port: -1
    # 配置协议级别的缓存控制
    cache-file: false
  registry:
    address: nacos://localhost:8848
    timeout: 5000
    # 配置注册中心缓存
    cache-file: false
    # 禁用注册中心文件缓存
    file: false
  consumer:
    timeout: 3000
    retries: 1
    check: false
    # 禁用消费者缓存
    cache-file: false
    # 配置消费者元数据类型
    metadata-type: local
  provider:
    timeout: 3000
    retries: 1
    # 禁用提供者缓存
    cache-file: false
    # 配置提供者元数据类型
    metadata-type: local
  # 全局配置
  config-center:
    timeout: 2000
    # 禁用配置中心文件缓存
    file: false
  metadata-report:
    timeout: 2000
    # 禁用元数据报告文件缓存
    file: false

# Elasticsearch配置 - 测试环境
elasticsearch:
  enabled: false  # 测试环境禁用ES
  host: localhost
  port: 9200
  scheme: http
  username: 
  password:
