# RabbitMQ配置
# 所有配置都从环境变量或配置文件读取，避免硬编码
rabbitmq:
  # 基础连接配置
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:guest}
  password: ${RABBITMQ_PASSWORD:guest}
  virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
  
  # 连接池配置
  connection:
    # 连接超时时间
    timeout: ${RABBITMQ_CONNECTION_TIMEOUT:30000}
    # 心跳间隔
    heartbeat: ${RABBITMQ_CONNECTION_HEARTBEAT:60}
    # 自动重连
    automatic-recovery: ${RABBITMQ_CONNECTION_AUTOMATIC_RECOVERY:true}
    # 网络恢复间隔
    network-recovery-interval: ${RABBITMQ_CONNECTION_NETWORK_RECOVERY_INTERVAL:5000}
  
  # 消费者配置
  consumer:
    # 默认消费模式
    default-mode: ${RABBITMQ_CONSUMER_DEFAULT_MODE:PUSH}
    # 默认确认模式
    default-ack-mode: ${RABBITMQ_CONSUMER_DEFAULT_ACK_MODE:MANUAL}
    # 预取数量
    prefetch-count: ${RABBITMQ_CONSUMER_PREFETCH_COUNT:1}
    # 批量大小
    batch-size: ${RABBITMQ_CONSUMER_BATCH_SIZE:100}
    # 消费间隔（毫秒）
    consume-interval: ${RABBITMQ_CONSUMER_CONSUME_INTERVAL:1000}
    # 最大重试次数
    max-retry-times: ${RABBITMQ_CONSUMER_MAX_RETRY_TIMES:3}
    # 超时时间
    timeout: ${RABBITMQ_CONSUMER_TIMEOUT:30000}
  
  # 生产者配置
  producer:
    # 确认模式
    confirm-mode: ${RABBITMQ_PRODUCER_CONFIRM_MODE:CORRELATED}
    # 返回模式
    return-mode: ${RABBITMQ_PRODUCER_RETURN_MODE:BASIC}
    # 批量发送大小
    batch-size: ${RABBITMQ_PRODUCER_BATCH_SIZE:100}
    # 发送超时时间
    timeout: ${RABBITMQ_PRODUCER_TIMEOUT:5000}
  
  # 队列配置
  queue:
    # 默认队列类型
    default-type: ${RABBITMQ_QUEUE_DEFAULT_TYPE:CLASSIC}
    # 是否持久化
    durable: ${RABBITMQ_QUEUE_DURABLE:true}
    # 是否排他
    exclusive: ${RABBITMQ_QUEUE_EXCLUSIVE:false}
    # 是否自动删除
    auto-delete: ${RABBITMQ_QUEUE_AUTO_DELETE:false}
    # 最大优先级
    max-priority: ${RABBITMQ_QUEUE_MAX_PRIORITY:10}
    # 最大长度
    max-length: ${RABBITMQ_QUEUE_MAX_LENGTH:10000}
    # 消息TTL（毫秒）
    message-ttl: ${RABBITMQ_QUEUE_MESSAGE_TTL:86400000}
  
  # 交换机配置
  exchange:
    # 默认交换机类型
    default-type: ${RABBITMQ_EXCHANGE_DEFAULT_TYPE:DIRECT}
    # 是否持久化
    durable: ${RABBITMQ_EXCHANGE_DURABLE:true}
    # 是否自动删除
    auto-delete: ${RABBITMQ_EXCHANGE_AUTO_DELETE:false}
    # 是否内部交换机
    internal: ${RABBITMQ_EXCHANGE_INTERNAL:false}
  
  # 死信队列配置
  dead-letter:
    # 死信交换机前缀
    exchange-prefix: ${RABBITMQ_DEAD_LETTER_EXCHANGE_PREFIX:dlx.}
    # 死信路由键前缀
    routing-key-prefix: ${RABBITMQ_DEAD_LETTER_ROUTING_KEY_PREFIX:dlq.}
    # 死信队列前缀
    queue-prefix: ${RABBITMQ_DEAD_LETTER_QUEUE_PREFIX:dlq.}
    # 是否启用死信队列
    enabled: ${RABBITMQ_DEAD_LETTER_ENABLED:true}
  
  # 延迟队列配置
  delay:
    # 是否启用延迟队列
    enabled: ${RABBITMQ_DELAY_ENABLED:true}
    # 延迟交换机前缀
    exchange-prefix: ${RABBITMQ_DELAY_EXCHANGE_PREFIX:delay.}
    # 延迟队列前缀
    queue-prefix: ${RABBITMQ_DELAY_QUEUE_PREFIX:delay.}
    # 默认延迟时间（毫秒）
    default-ttl: ${RABBITMQ_DELAY_DEFAULT_TTL:30000}
  
  # 优先级队列配置
  priority:
    # 是否启用优先级队列
    enabled: ${RABBITMQ_PRIORITY_ENABLED:true}
    # 最大优先级
    max-priority: ${RABBITMQ_PRIORITY_MAX_PRIORITY:10}
    # 默认优先级
    default-priority: ${RABBITMQ_PRIORITY_DEFAULT_PRIORITY:5}
  
  # 集群配置
  cluster:
    # 是否启用集群
    enabled: ${RABBITMQ_CLUSTER_ENABLED:false}
    # 集群节点列表
    nodes: ${RABBITMQ_CLUSTER_NODES:}
    # 负载均衡策略
    load-balance: ${RABBITMQ_CLUSTER_LOAD_BALANCE:ROUND_ROBIN}
  
  # 监控配置
  monitoring:
    # 是否启用监控
    enabled: ${RABBITMQ_MONITORING_ENABLED:true}
    # 监控间隔（秒）
    interval: ${RABBITMQ_MONITORING_INTERVAL:30}
    # 是否记录详细日志
    verbose-logging: ${RABBITMQ_MONITORING_VERBOSE_LOGGING:false}

# 配置说明：
# 1. 所有配置都支持环境变量覆盖，格式：${ENV_VAR_NAME:default_value}
# 2. 环境变量优先级高于配置文件
# 3. 如果没有环境变量，则使用配置文件中的默认值
# 4. 支持不同环境的配置覆盖（dev, test, prod等）
# 5. 集群节点配置支持逗号分隔的字符串，如：node1:5672,node2:5672
