# Nacos配置中心配置文件
# 此文件用于导入到Nacos配置中心
# Data ID: messages-service.yml
# Group: JIANGYANG
# 格式: YAML

# 动态数据源配置
spring:
  datasource:
    dynamic:
      enabled: true
      primary: master
      strict: false
      seata: true
      datasource:
        # 主数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.133.246.113:3306/messages_service?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: bgtech
          password: Zly689258..
          type: com.alibaba.druid.pool.DruidDataSource
          pool:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall,slf4j
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        
        # 从数据源
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.133.246.113:3306/messages_service_slave?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: bgtech
          password: Zly689258..
          type: com.alibaba.druid.pool.DruidDataSource
          pool:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall,slf4j
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        
        # 审计日志数据源
        audit:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.133.246.113:3306/messages_service_audit?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: bgtech
          password: Zly689258..
          type: com.alibaba.druid.pool.DruidDataSource
          pool:
            initial-size: 3
            min-idle: 3
            max-active: 10
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall,slf4j
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# 消息服务配置
message:
  service:
    # 消息服务类型：rocketmq, kafka, rabbitmq
    type: rocketmq
    
    # 是否启用消息轨迹追踪
    trace-enabled: true
    
    # 消息发送重试次数
    send-retry-times: 3
    
    # 消息发送超时时间（毫秒）
    send-timeout-ms: 5000
    
    # 最大批量发送消息数量
    max-batch-size: 100
    
    # RocketMQ配置
    rocketmq:
      # 是否启用RocketMQ
      enabled: true
      # Name Server地址
      name-server: ${ROCKETMQ_NAMESRV_ADDR:8.133.246.113:9876}
      # 生产者组
      producer:
        group: jiangyang-producer-group
        send-message-timeout: 3000
        retry-times-when-send-failed: 3
        retry-times-when-send-async-failed: 3
        compress-message-body-threshold: 4096
        max-message-size: 4194304
      # 消费者组
      consumer:
        group: jiangyang-consumer-group
      # 是否启用消息轨迹
      enable-msg-trace: true
      # 消息轨迹存储类型
      trace-topic-name: RMQ_SYS_TRACE_TOPIC
    
    # Kafka配置
    kafka:
      # 是否启用Kafka
      enabled: false
      # Bootstrap Servers地址
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:8.133.246.113:9092}
      # 消费者组ID
      consumer-group-id: jiangyang-consumer-group
      # 生产者确认机制：acks
      acks: all
      # 批量大小（字节）
      batch-size: 16384
      # 延迟时间（毫秒）
      linger-ms: 1
      # 缓冲区大小（字节）
      buffer-memory: 33554432
      # 生产者重试次数
      retries: 3
      # 消费者自动提交间隔
      auto-commit-interval-ms: 1000
      # 消费者会话超时时间
      session-timeout-ms: 30000
      # 消费者心跳间隔
      heartbeat-interval-ms: 3000
      # 消费者最大拉取记录数
      max-poll-records: 500
      # 消费者最大拉取间隔
      max-poll-interval-ms: 300000
    
    # RabbitMQ配置
    rabbitmq:
      # 是否启用RabbitMQ
      enabled: false
      # 主机地址
      host: ${RABBITMQ_HOST:8.133.246.113}
      # 端口
      port: ${RABBITMQ_PORT:5672}
      # 用户名
      username: ${RABBITMQ_USERNAME:guest}
      # 密码
      password: ${RABBITMQ_PASSWORD:guest}
      # 虚拟主机
      virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
      # 连接超时时间（毫秒）
      connection-timeout: 60000
      # 心跳间隔（秒）
      heartbeat: 60
      # 连接池大小
      connection-pool-size: 10
      # 通道池大小
      channel-pool-size: 25
      # 是否启用发布确认
      publisher-confirms: true
      # 是否启用发布返回
      publisher-returns: true
      # 消息确认超时时间
      confirm-timeout: 5000
      # 返回超时时间
      return-timeout: 5000

# 日志配置
logging:
  level:
    com.jiangyang.messages: INFO
    org.apache.rocketmq: WARN
    org.apache.kafka: WARN
    com.rabbitmq: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/messages-service.log
    max-size: 100MB
    max-history: 30

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      # 禁用数据源健康检查，因为使用动态数据源
      group:
        db:
          include: none
  health:
    # 禁用默认的数据源健康检查
    db:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true

# 线程池配置
thread:
  pool:
    core-size: 10
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    thread-name-prefix: messages-service-
