-- 检查 Quartz 表是否存在
USE metersphere;

-- 检查所有 QRTZ_ 开头的表
SHOW TABLES LIKE 'QRTZ_%';

-- 如果表不存在，使用以下命令创建
-- CREATE TABLE QRTZ_JOB_DETAILS (
--   SCHED_NAME VARCHAR(120) NOT NULL,
--   JOB_NAME VARCHAR(200) NOT NULL,
--   JOB_GROUP VARCHAR(200) NOT NULL,
--   DESCRIPTION VARCHAR(250) NULL,
--   JOB_CLASS_NAME VARCHAR(250) NOT NULL,
--   IS_DURABLE VARCHAR(1) NOT NULL,
--   IS_NONCONCURRENT VARCHAR(1) NOT NULL,
--   IS_UPDATE_DATA VARCHAR(1) NOT NULL,
--   REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
--   JOB_DATA BLOB NULL,
--   PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE TABLE QRTZ_TRIGGERS (
--   SCHED_NAME VARCHAR(120) NOT NULL,
--   TRIGGER_NAME VARCHAR(200) NOT NULL,
--   TRIGGER_GROUP VARCHAR(200) NOT NULL,
--   JOB_NAME VARCHAR(200) NOT NULL,
--   JOB_GROUP VARCHAR(200) NOT NULL,
--   DESCRIPTION VARCHAR(250) NULL,
--   NEXT_FIRE_TIME BIGINT(13) NULL,
--   PREV_FIRE_TIME BIGINT(13) NULL,
--   PRIORITY INTEGER NULL,
--   TRIGGER_STATE VARCHAR(16) NOT NULL,
--   TRIGGER_TYPE VARCHAR(8) NOT NULL,
--   START_TIME BIGINT(13) NOT NULL,
--   END_TIME BIGINT(13) NULL,
--   CALENDAR_NAME VARCHAR(200) NULL,
--   MISFIRE_INSTR SMALLINT(2) NULL,
--   JOB_DATA BLOB NULL,
--   PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
--   FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP) REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- CREATE TABLE QRTZ_SCHEDULER_STATE (
--   SCHED_NAME VARCHAR(120) NOT NULL,
--   INSTANCE_NAME VARCHAR(200) NOT NULL,
--   LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
--   CHECKIN_INTERVAL BIGINT(13) NOT NULL,
--   PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
