# DeepSearch Service 主配置文件

spring:
  application:
    name: chat-agent-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true
    lazy-initialization: false
  datasource:
    dynamic:
      seata: false  # 禁用Seata分布式事务

# 服务配置
service:
  name: chat-agent-service
  version: 1.0.0

# Seata配置 - 完全禁用
seata:
  enabled: false
  auto-data-source-proxy: false
  enable-auto-data-source-proxy: false
  application-id: ${spring.application.name}
  tx-service-group: chat-agent-service-group
  service:
    vgroup-mapping:
      chat-agent-service-group: default
    grouplist:
      default: 8.133.246.113:8091
    enable-degrade: false
    disable-global-transaction: true
  client:
    rm:
      report-success-enable: false
      table-meta-check-enable: false
      report-retry-count: 0
      async-commit-buffer-limit: 0
    tm:
      commit-retry-count: 0
      rollback-retry-count: 0
      default-global-transaction-timeout: 0
      degrade-check: false
      degrade-check-allow-times: 0
      degrade-check-period: 0

