# Chat-Agent 开发环境配置

spring:
  datasource:
    dynamic:
      seata: false
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/chat_agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: root
          pool:
            initial-size: 5
            min-idle: 5
            max-active: 20
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
            connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  
  # AI配置
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-demo-key-for-development-only}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 1000
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY:demo-key-for-development-only}
        endpoint: ${AZURE_OPENAI_ENDPOINT:https://demo.openai.azure.com}
        chat:
          options:
            deployment-name: ${AZURE_OPENAI_DEPLOYMENT_NAME:gpt-35-turbo}
            temperature: 0.7
            max-tokens: 1000
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:llama2}
          temperature: 0.7

# 禁用Seata
seata:
  enabled: false
  auto-data-source-proxy: false
  enable-auto-data-source-proxy: false
  disable-global-transaction: true

# 日志配置
logging:
  level:
    io.seata: OFF
    com.jiangyang.base.config: DEBUG
    org.springframework.ai: DEBUG
