-- API 客户端表
CREATE TABLE IF NOT EXISTS api_client (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_id VARCHAR(64) NOT NULL UNIQUE,
  client_name VARCHAR(128) NOT NULL,
  description VARCHAR(255),
  status TINYINT DEFAULT 1 COMMENT '1:启用,0:禁用',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- API Key 表
CREATE TABLE IF NOT EXISTS api_key (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  api_key VARCHAR(64) NOT NULL UNIQUE,
  client_id VARCHAR(64) NOT NULL,
  client_name VARCHAR(128),
  description VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME,
  active TINYINT DEFAULT 1,
  CONSTRAINT fk_client_id FOREIGN KEY (client_id) REFERENCES api_client(client_id)
); 