-- API 配置表
CREATE TABLE IF NOT EXISTS api_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_name VARCHAR(64) NOT NULL COMMENT 'API配置名称',
  api_url VARCHAR(255) NOT NULL COMMENT 'API地址',
  api_key VARCHAR(255) NOT NULL COMMENT 'API密钥',
  model_name VARCHAR(64) NOT NULL COMMENT '模型名称',
  model_type VARCHAR(32) NOT NULL COMMENT '模型类型',
  user_id VARCHAR(64) COMMENT '用户ID',
  enabled TINYINT DEFAULT 1 COMMENT '是否启用',
  is_default TINYINT DEFAULT 0 COMMENT '是否默认',
  priority INT DEFAULT 0 COMMENT '优先级',
  description VARCHAR(255) COMMENT '描述',
  create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
); 