org.quartz.scheduler.instanceName=msScheduler
org.quartz.scheduler.instanceId=AUTO

org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.tablePrefix=QRTZ_
org.quartz.jobStore.isClustered=false
org.quartz.jobStore.useProperties=false
org.quartz.jobStore.dataSource=quartz

org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=10
org.quartz.threadPool.threadPriority=5
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

org.quartz.dataSource.quartz.driver=com.mysql.cj.jdbc.Driver
org.quartz.dataSource.quartz.URL=jdbc:mysql://8.133.246.113:3306/metersphere?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
org.quartz.dataSource.quartz.user=bgtech
org.quartz.dataSource.quartz.password=Zly689258..
org.quartz.dataSource.quartz.maxConnections=10
