server:
  port: 8091

spring:
  application:
    name: seata-server

seata:
  config:
    type: nacos
    nacos:
      server-addr: 8.133.246.113:8848
      namespace: d750d92e-152f-4055-a641-3bc9dda85a29
      group: DEFAULT_GROUP
      data-id: seataServer.properties
      username: ""
      password: ""
  
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 8.133.246.113:8848
      namespace: d750d92e-152f-4055-a641-3bc9dda85a29
      group: DEFAULT_GROUP
      cluster: default
      username: ""
      password: ""

  store:
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.133.246.113:3306/seata?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
      user: bgtech
      password: Zly689258..
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      lock-retry-interval: 10
      lock-retry-times: 30
      lock-retry-policy-branch-rollback-on-conflict: true
      max-wait: 5000

  # 控制台配置
  console:
    user:
      username: admin
      password: admin
    auth:
      enabled: false

  log:
    exception-rate: 100

logging:
  level:
    io.seata: DEBUG
    io.seata.server: DEBUG
