# DeepSearch Service 主配置文件

spring:
  application:
    name: deepSearch-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
    allow-circular-references: true
    allow-bean-definition-overriding: true
    lazy-initialization: false

# 服务配置
service:
  name: deepSearch-service
  version: 1.0.0

