# 开发环境配置

# 服务配置 - 开发环境
service:
  ai-agent:
    base-url: http://localhost:8080
    timeout: 30000
  bgai:
    base-url: http://localhost:8081
    timeout: 30000

# 数据源配置 - 开发环境
spring:
  datasource:
    dynamic:
      enabled: true
      primary: master
      strict: false
      seata: true
      
      datasource:
        # 主数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.133.246.113:3306/deepsearch_service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: bgtech
          password: Zly689258..
          type: com.alibaba.druid.pool.DruidDataSource
          pool:
            initial-size: 5
            min-idle: 10
            max-active: 20
            max-wait: 60000
            validation-query: SELECT 1
            test-while-idle: true
            filters: stat,wall
        
        # 从数据源
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://8.133.246.113:3306/deepsearch_service?useUnicode=true&characterEncoding=UTF-8&useSSL=false
          username: bgtech
          password: Zly689258..
          type: com.alibaba.druid.pool.DruidDataSource
          pool:
            initial-size: 5
            min-idle: 10
            max-active: 20
            max-wait: 60000
            validation-query: SELECT 1
            test-while-idle: true
            filters: stat,wall

# 日志配置 - 开发环境
logging:
  level:
    com.jiangyang.datacalculation: DEBUG
    com.jiangyang.base: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.nacos: DEBUG
