apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service-account
  namespace: jiangyangai
  labels:
    app: gateway-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gateway-service-role
  namespace: jiangyangai
rules:
# 允许读取ConfigMap和Secret
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# 允许读取Pod信息
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# 允许读取Service信息
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# 允许读取Endpoints信息
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# 允许读取事件信息
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
# 允许读取节点信息
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-service-role-binding
  namespace: jiangyangai
subjects:
- kind: ServiceAccount
  name: gateway-service-account
  namespace: jiangyangai
roleRef:
  kind: Role
  name: gateway-service-role
  apiGroup: rbac.authorization.k8s.io
---
# 集群级别的权限（用于服务发现）
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-service-cluster-role
rules:
# 允许读取所有命名空间的Service和Endpoints
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# 允许读取所有命名空间的Pod
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# 允许读取所有命名空间的节点信息
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-service-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: gateway-service-account
  namespace: jiangyangai
roleRef:
  kind: ClusterRole
  name: gateway-service-cluster-role
  apiGroup: rbac.authorization.k8s.io 