# 开发环境配置
spring:
  profiles:
    active: dev

# 服务配置 - 开发环境
service:
  ai-agent:
    base-url: http://localhost:8080
    timeout: 30000
  bgai:
    base-url: http://localhost:8081
    timeout: 30000

# 日志配置 - 开发环境
logging:
  level:
    com.jiangyang.datacalculation: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
