spring:
  webflux:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      max-in-memory-size: 512KB
  main:
    web-application-type: reactive
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务
  application:
    name: bgai-service
  config:
    import:
      - optional:classpath:deepseek-config.properties
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:8.133.246.113}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:d750d92e-152f-4055-a641-3bc9dda85a29}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
        # 增加关闭连接的配置
        shutdown-timeout: 5000
        watch-delay: 10000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml
        # 警告处理配置
        handle-warnings: true
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
        # 设置超时时间，防止长时间等待
        timeout: 5000
        refresh-enabled: true
        # 增加关闭连接的配置
        shutdown-timeout: 5000
        extension-configs:
          - data-id: client-config.yaml
            group: ${spring.cloud.nacos.discovery.group}
            refresh: true
        # 使用默认缓存目录，确保容器能正确访问
        shared-configs:
          - data-id: common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            group: ${spring.cloud.nacos.discovery.group}
            refresh: true

# SpringDoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
    
# Dubbo配置
dubbo:
  # 禁用文件型缓存与服务名映射，避免使用用户目录下的 .dubbo 缓存
  application:
    metadata-type: local
  service-name-mapping:
    enabled: false
    cache:
      file:
        enabled: false
  cache:
    file:
      enabled: false
  metadata-report:
    file: false
  config-center:
    file: false
  # 注册中心本地文件缓存禁用（不同版本属性可能略有差异，双保险）
  registry:
    file: false
    cache-file: false

# Seata 分布式事务配置（修复 vgroupMapping 缺失导致的启动报错）
seata:
  enabled: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      default: 8.133.246.113:8091
  registry:
    type: file
    file:
      name: file.conf
  config:
    type: file
    file:
      name: file.conf

# 自定义配置
bgai:
  nacos:
    shutdown:
      enabled: true # 启用Nacos连接关闭处理器
      timeout: 5000 # Nacos客户端关闭超时时间(毫秒)

# 禁用Actuator Metrics
management:
  simple:
    metrics:
      export:
        enabled: false
  metrics:
    enable:
      all: false
