spring:
  webflux:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      max-in-memory-size: 512KB
  main:
    web-application-type: reactive
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务
  application:
    name: bgai-service
  config:
    import:
      - optional:classpath:deepseek-config.properties
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:8.133.246.113}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:354d4858-c584-4524-8edc-95f0b1ffab48}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml
        # 警告处理配置
        handle-warnings: true
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
        # 设置超时时间，防止长时间等待
        timeout: 5000
        refresh-enabled: true
        # 使用默认缓存目录，确保容器能正确访问
        shared-configs:
          - data-id: common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            group: ${spring.cloud.nacos.discovery.group}
            refresh: true
