spring:
  webflux:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      max-in-memory-size: 512KB
  main:
    web-application-type: reactive
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务
  application:
    name: bgai-service
  config:
    import:
      - optional:classpath:deepseek-config.properties
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:8.133.246.113}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:d750d92e-152f-4055-a641-3bc9dda85a29}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
        # 增加关闭连接的配置
        shutdown-timeout: 5000
        watch-delay: 10000
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
        group: ${spring.cloud.nacos.discovery.group}
        file-extension: yaml
        # 警告处理配置
        handle-warnings: true
        # 使配置失败时更友好的处理，不会导致应用启动失败
        fail-fast: false
        # 设置超时时间，防止长时间等待
        timeout: 5000
        refresh-enabled: true
        # 增加关闭连接的配置
        shutdown-timeout: 5000
        extension-configs:
          - data-id: client-config.yaml
            group: ${spring.cloud.nacos.discovery.group}
            refresh: true
        # 使用默认缓存目录，确保容器能正确访问
        shared-configs:
          - data-id: common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
            group: ${spring.cloud.nacos.discovery.group}
            refresh: true

# SpringDoc配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**
    
# 自定义配置
bgai:
  nacos:
    shutdown:
      enabled: true # 启用Nacos连接关闭处理器
      timeout: 5000 # Nacos客户端关闭超时时间(毫秒)

# 禁用Actuator Metrics
management:
  simple:
    metrics:
      export:
        enabled: false
  metrics:
    enable:
      all: false

# Seata分布式事务配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  timeout: 60000
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT

  # 注册中心配置
  registry:
    type: nacos
    nacos:
      server-addr: 8.133.246.113:8848
      namespace: d750d92e-152f-4055-a641-3bc9dda85a29
      group: DEFAULT_GROUP
      cluster: default


  # 配置中心配置
  config:
    type: nacos
    nacos:
      server-addr: 8.133.246.113:8848
      namespace: d750d92e-152f-4055-a641-3bc9dda85a29
      group: DEFAULT_GROUP
      data-id: seataServer.properties


  # 事务存储配置
  store:
    mode: db
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://8.133.246.113:3306/seata?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
      user: bgtech
      password: Zly689258..
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      lock-retry-interval: 10
      lock-retry-times: 30
      lock-retry-policy-branch-rollback-on-conflict: true
      max-wait: 5000

  # Saga模式配置
  saga:
    enabled: true
    mode: state-machine
    state-machine:
      enable: true
      auto-register: false
      enable-async: true
      thread-pool-size: 16
      default-transaction-timeout: 30
      enable-transaction-timeout-check: true
      transaction-recovery-interval-seconds: 120
      concurrent-request-size: 2000
      saga-limit: 1000
      saga-retry-interval: 1
      saga-compensation-persist-mode: forward
      saga-compensation-lock-mode: optimistic
      saga-json-parser: fastjson
      saga-branch-register-enable: false

  # 客户端配置
  client:
    rm:
      report-success-enable: false
      table-meta-check-enable: false
      report-retry-count: 5
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
      default-global-transaction-timeout: 60
      degrade-check: false
      degrade-check-allow: false
      degrade-check-period: 2000
      interceptor-order: -2147482648

  # 服务端配置
  service:
    vgroup-mapping:
      bgai-service-tx-group: default
    grouplist:
      default: 8.133.246.113:8091
    enable-degrade: false
    disable-global-transaction: false

  # 日志配置
  log:
    exception-rate: 100

# 日志级别配置
logging:
  level:
    io.seata: DEBUG
    com.bgpay.bgai: DEBUG
    com.jiangyang.base: DEBUG